
3, 1235, Reema, computer,06:13:29,23/05/2024,Present
3, 1235, Reema, computer,06:13:29,23/05/2024,Present
3, 1235, Reema, computer,06:13:29,23/05/2024,Present
3, 1235, Reema, computer,06:13:29,23/05/2024,Present
3, 1235, Reema, computer,06:13:29,23/05/2024,Present
3, 1235, Reema, computer,06:13:29,23/05/2024,Present
3, 1235, Reema, computer,06:13:29,23/05/2024,Present
3, 1235, Reema, computer,06:13:29,23/05/2024,Present
3, 1235, Reema, computer,06:13:29,23/05/2024,Present


('8',), ('899',), ('Manish',), ('computer',),09:12:42,24/05/2024,Present
('8',), ('899',), ('Manish',), ('computer',),09:12:43,24/05/2024,Present
('8',), ('899',), ('Manish',), ('computer',),09:13:43,24/05/2024,Present
('8',), ('899',), ('Manish',), ('computer',),09:13:44,24/05/2024,Present
None, None, None, None,09:14:58,24/05/2024,Present
('4',), ('125',), ('Ananya Mishra',), ('computer',),11:51:08,24/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),11:51:09,24/05/2024,Present
('4',), ('125',), ('Ananya Mishra',), ('computer',),11:51:09,24/05/2024,Present
('4',), ('125',), ('Ananya Mishra',), ('computer',),11:51:10,24/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),11:51:11,24/05/2024,Present
('4',), ('125',), ('Ananya Mishra',), ('computer',),11:51:11,24/05/2024,Present
('4',), ('125',), ('Ananya Mishra',), ('computer',),11:51:11,24/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),11:51:12,24/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),11:51:12,24/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),11:51:12,24/05/2024,Present
('4',), ('125',), ('Ananya Mishra',), ('computer',),11:51:13,24/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),11:51:13,24/05/2024,Present
('4',), ('125',), ('Ananya Mishra',), ('computer',),11:51:13,24/05/2024,Present
('4',), ('125',), ('Ananya Mishra',), ('computer',),11:51:14,24/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),11:56:20,24/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),11:56:20,24/05/2024,Present
('6',), ('123',), ('Shashi',), ('computer',),11:59:59,24/05/2024,Present
('4',), ('125',), ('Ananya Mishra',), ('computer',),12:00:08,24/05/2024,Present
('4',), ('125',), ('Ananya Mishra',), ('computer',),12:00:08,24/05/2024,Present
('6',), ('123',), ('Shashi',), ('computer',),12:00:09,24/05/2024,Present
('6',), ('123',), ('Shashi',), ('computer',),12:00:09,24/05/2024,Present
('6',), ('123',), ('Shashi',), ('computer',),12:00:37,24/05/2024,Present
('6',), ('123',), ('Shashi',), ('computer',),12:00:37,24/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),23:49:20,25/05/2024,Present
('6',), ('123',), ('Shashi',), ('computer',),23:49:50,25/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),23:49:50,25/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),23:49:51,25/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),23:49:51,25/05/2024,Present
('6',), ('123',), ('Shashi',), ('computer',),23:49:52,25/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),23:50:00,25/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:42,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:42,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:42,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:43,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:43,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:43,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:44,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:44,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:44,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:45,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:45,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:45,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:45,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:46,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:46,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:46,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:47,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:47,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:47,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:47,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:48,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:48,26/05/2024,Present
('6',), ('123',), ('Shashi',), ('computer',),05:39:54,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:55,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:55,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:56,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:57,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:58,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:58,26/05/2024,Present
('3',), ('1235',), ('Reema verma',), ('computer',),05:39:59,26/05/2024,Present
